name: neomorphic_design
description: A set of neomorphic design based widgets.
version: 0.0.1
author: Camillo Bucciarelli

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: